spring.application.name=timewise-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/timewise
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080

spring.scheduling.enabled=true
